apache:
  image: dockerizedrupal/apache-2.4:2.0.0
  hostname: apache
  ports:
    - "80:80"
    - "443:443"
  volumes_from:
    - apache-data
  links:
    - php
apache-data:
  image: dockerizedrupal/apache-2.4:2.0.0
  hostname: apache-data
  entrypoint: ["/bin/echo", "Data-only container for Apache."]
  volumes:
    - .:/apache/data
php:
  image: dockerizedrupal/php-7.1:2.0.0
  hostname: php
  environment:
    - SERVER_NAME=localhost
    - TIMEZONE=Etc/UTC
    - DRUPAL_VERSION=8
    - DRUSH_VERSION=8
    - SMTP_HOST=
    - SMTP_PORT=25
    - SMTP_FROM=
    - SMTP_USERNAME=
    - SMTP_PASSWORD=
    - MYSQL_HOST=
    - MYSQL_PORT=3306
    - MYSQL_MAX_ALLOWED_PACKET=512M
    - MEMCACHED_HOST=
    - MEMCACHED_PORT=11211
    - REDIS_HOST=
    - REDIS_PORT=6379
    - PHP_INI_REALPATH_CACHE_SIZE=256k
    - PHP_INI_REALPATH_CACHE_TTL=3600
    - PHP_INI_POST_MAX_SIZE=512M
    - PHP_INI_TIMEZONE=UTC
    - PHP_INI_UPLOAD_MAX_FILESIZE=512M
    - PHP_INI_SHORT_OPEN_TAG=On
    - PHP_INI_MAX_EXECUTION_TIME=300
    - PHP_INI_MAX_INPUT_VARS=4096
    - PHP_INI_MEMORY_LIMIT=512M
    - PHP_INI_DISPLAY_ERRORS=On
    - PHP_INI_DISPLAY_STARTUP_ERRORS=On
    - PHP_INI_ERROR_REPORTING=E_ALL
    - PHP_INI_EXPOSE_PHP=On
    - PHP_INI_ALLOW_URL_FOPEN=On
    - PHP_INI_OPCACHE=On
    - PHP_INI_OPCACHE_MEMORY_CONSUMPTION=2048
    - PHP_INI_XDEBUG=On
    - PHP_INI_XDEBUG_REMOTE_PORT=9000
    - PHP_INI_XDEBUG_REMOTE_HOST=127.0.0.1
    - PHP_INI_XDEBUG_REMOTE_CONNECT_BACK=On
    - PHP_INI_XDEBUG_IDEKEY=PHPSTORM
    - PHP_INI_XDEBUG_VAR_DISPLAY_MAX_DEPTH=5
    - PHP_INI_MEMCACHED=On
    - PHP_INI_REDIS=On
    - PHP_INI_BLACKFIRE=On
    - PHP_INI_BLACKFIRE_SERVER_ID=
    - PHP_INI_BLACKFIRE_SERVER_TOKEN=
    - PHP_INI_APCU=On
    - PHP_INI_APD=On
    - PHP_FPM_PM=dynamic
    - PHP_FPM_PM_MAX_CHILDREN=5
    - PHP_FPM_PM_START_SERVERS=2
    - PHP_FPM_PM_MIN_SPARE_SERVERS=1
    - PHP_FPM_PM_MAX_SPARE_SERVERS=3
    - PHP_FPM_PM_PROCESS_IDLE_TIMEOUT=10s
    - PHP_FPM_PM_MAX_REQUESTS=0
    - CRON=On
    - CRONTAB_1_MAILTO=
    - CRONTAB_1_EXPRESSION=
    - CRONTAB_1_COMMAND=
    - USER_ID=
    - GROUP_ID=
